'use strict';


// We select all the elements that we need to maipulate and store them in variables.
const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');

// Here when we want to select multiple elements having same class/selector , querySelector() method will select only the first element.
//const btnsShowModal = document.querySelector('.show-modal');
//console.log(btnsShowModal);

// This querySelectorAll() method selects all the elements with same selector and stores the elements as a NodeList (which is simply an array of selected elements index starting from 0).
const btnsShowModal = document.querySelectorAll('.show-modal');
console.log(btnsShowModal);


const openModal = function() {
    //console.log('Button clicked');

    // Manipulating Classes to display the modal
    // 1. classList  - we can read this method on a selected element
    // 2. remove - classList has a couple of methods like this ,
    modal.classList.remove('hidden');
    overlay.classList.remove('hidden');

    //modal.style.display = 'block'; We would have done this individually for display property , but if we have like 10 properties then it wouldnt be possible ,
    // So we aggregate all the styles into one class and add/remove classes as we need or dont need those styles. 
} ; 


const closeModal = function() {
    modal.classList.add('hidden'); // We are not selecting the class here ,so we dont use '.hidden' 
    overlay.classList.add('hidden'); 
};



// using a for loop , which is the best method to loop through arrays and access array elements.
for(let i=0 ; i<btnsShowModal.length ; i++){
    btnsShowModal[i].addEventListener('click' ,openModal); //We're just declaring the function here.
}



// Remember we're not calling the function ,it is the javascript engine who will call the function as soon as the click event on the element happens.

//btnCloseModal.addEventListener('click', closeModal());This wouldnot work at all , the function will be executed immediately as soon as javascript executes this line.
btnCloseModal.addEventListener('click', closeModal);


overlay.addEventListener('click', closeModal);
//overlay.addEventListener('click',function() {
//modal.classList.add('hidden'); // We are not selecting the class here,so we dont use '.hidden' 
//    overlay.classList.add('hidden'); 
//});


document.addEventListener('keydown' , function(e){
    console.log('Key pressed on keyboard');// This happens as soon as we press any key on the keyboard.
    console.log(e); // typeof e is object , i.e generated by Javascript. 
    console.log(e.key);

    if(e.key === 'Escape' && !modal.classList.contains('hidden')){// We want to close the modal only when the model doesnt contain 'hidden' class.
        console.log('Esc was pressed');
        
        closeModal(); // We need to call this function here not just declaring.
    }

} );

// modal.classList.contains('hidden') method checks if the element has the class 'hidden' or not and returns a boolean .



// 3 methods that we used on class :
// - element.classList.add()
// - element.classList.remove()
// - element.classList.contains()